zero  (f, x) { x }
one   (f, x) { f(x) }
two   (f, x) { f(f(x)) }
three (f, x) { f(f(f(x))) }
four  (f, x) { f(f(f(f(x)))) }
five  (f, x) { f(f(f(f(f(x))))) }
six   (f, x) { f(f(f(f(f(f(x)))))) }
seven (f, x) { f(f(f(f(f(f(f(x))))))) }
eight (f, x) { f(f(f(f(f(f(f(f(x)))))))) }
nine  (f, x) { f(f(f(f(f(f(f(f(f(x))))))))) }
ten   (f, x) { f(f(f(f(f(f(f(f(f(f(x)))))))))) }

add1(n) {
  (f, x) {
    f(n(f, x))
  }
}

add(m, n) {
  (f, x) {
    m(f, n(f, x))
  }
}

mul(m, n) {
  (f, x) {
    m(n(f), x)
  }
}

pow(m, n) {
  n(m)
}

one
add1(zero)

three
add1(add1(add1(zero)))

eight
add(two, six)
add(four, four)
mul(two, four)
mul(four, two)
